# Generated by Django 3.0.4 on 2020-03-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=10)),
                ('valid_till', models.DateTimeField()),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lock')),
            ],
        ),
    ]
