# Generated by Django 3.0.4 on 2020-03-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200321_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='time',
            new_name='time_created',
        ),
    ]
