# Generated by Django 3.0.4 on 2020-03-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200321_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
