# Generated by Django 3.0.4 on 2020-03-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_otp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
