# Generated by Django 3.0.4 on 2020-03-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200322_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='time_remaining',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
