# Generated by Django 3.0.4 on 2020-04-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_otp_time_remaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('lock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Lock')),
                ('otp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.OTP')),
            ],
        ),
    ]
